#ifndef PROPULSION_H_
#define PROPULSION_H_

const double MAXFUEL = 1000.0; //max fuel capacity
const double C = 299792458.0; // speed of light C

class Propulsion{
    private:
        double fuelLevel;
        double lightToFuel; //amount of fuel generated by the propulsion system at any given time
        double lightLevel;

    public:
        Propulsion();
        Propulsion(double, double);
        bool consumeFuel(double);
        void addFuel();
        void generateFuel(double);
        void setLightLevel(double);
        void GenerateReport() const;
};

#endif //PROPULSION_SYS_H_